In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
%matplotlib qt
#%matplotlib inline

In [31]:
df = pd.DataFrame({'A':[0,1,1,0],'B':[0,1,0,1],'C':[1,1,1,1],'Out':[0,1,1,0]})

In [32]:
df

A  B  C  Out
0  0  0  1    0
1  1  1  1    1
2  1  0  1    1
3  0  1  1    0

In [18]:
in_cols=df.columns.drop('Out')

In [52]:
l0 = df[in_cols].values
y=np.array([df['Out'].tolist()]).T

Sigmod function: $S(t)=\frac{1}{1+e^{-t}}$

In [8]:
def nonlin(x, deriv=False):
    if(deriv==True):
        return x*(1-x)
    else:
        return 1.0/(1.0+np.exp(-x))
    

Note that the deriv part of the function is *not* the derivative wrt x. It gives the derivative wrt x when fed it's output, ie $\frac{dS(t)}{dt}=S(t)\times(1-S(t))$

Here's what it looks like:

In [9]:
XX=np.linspace(-6,6)
plt.plot(XX,nonlin(XX))
plt.show()

This is the derivative:

In [25]:
plt.plot(XX,nonlin(nonlin(XX),deriv=True))
plt.show()

Seed random numbers so that we have the same thing as the example.

In [43]:
np.random.seed(1)

Initialize the weights matrix:

In [49]:
syn0=2*np.random.random((3,1))-1

In [47]:
syn0

array([-0.39533485, -0.70648822, -0.81532281])

What would the output be now?

In [60]:
nonlin(np.dot(l0,syn0))

array([[ 0.00966955],
       [ 0.99211644],
       [ 0.99359061],
       [ 0.00786405]])

In [39]:
l1=nonlin(np.dot(l0,syn0))

array([[ 0.2689864 ],
       [ 0.3262757 ],
       [ 0.23762817],
       [ 0.36375058]])

In [37]:
l1

array([[ 0.2689864 ],
       [ 0.3262757 ],
       [ 0.23762817],
       [ 0.36375058]])

In [54]:
for iter in xrange(10000):
    
    #forward propagation
    l1=nonlin(np.dot(l0,syn0))
    
    #Ok, we tried. How much were we wrong by?
    l1_error = y-l1
    #fit using newton's method.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    syn0 += np.dot(l0.T,l1_delta)

In [55]:
l1

array([[ 0.00967004],
       [ 0.99211604],
       [ 0.99359029],
       [ 0.00786445]])

In [57]:
test=np.array([[1,0,0]])


In [58]:
testout=nonlin(np.dot(test,syn0))

In [59]:
testout

array([[ 0.99993702]])

### Something more complicated:

In [62]:
df = pd.DataFrame({'A':[0,0,1,1],'B':[0,1,0,1],'C':[1,1,1,1],'Out':[0,1,1,0]})
df

A  B  C  Out
0  0  0  1    0
1  0  1  1    1
2  1  0  1    1
3  1  1  1    0

Note: The output in this example is XOR(A,B)

In [63]:
l0 = df[in_cols].values
y=np.array([df['Out'].tolist()]).T

Initialize weights:

In [64]:
syn0 = 2*np.random.random((3,4))-1
syn1 = 2*np.random.random((4,1))-1